// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUDc7RPDJ3gzzq1pdvyEH9lkwP3IIzMLI',
    appId: '1:926177753172:web:9ba7922c085e400f3655c1',
    messagingSenderId: '926177753172',
    projectId: 'attendance-4e2af',
    authDomain: 'attendance-4e2af.firebaseapp.com',
    storageBucket: 'attendance-4e2af.firebasestorage.app',
    measurementId: 'G-HNTYV5346Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTVs0EHPGbT4uenuPc7knSWNea49wQ_ao',
    appId: '1:926177753172:android:4e5065873ef081f93655c1',
    messagingSenderId: '926177753172',
    projectId: 'attendance-4e2af',
    storageBucket: 'attendance-4e2af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJvS2mgyBkwtIRPBV5GSyIq9nqOhBRiw',
    appId: '1:926177753172:ios:543f9d1b0e9911593655c1',
    messagingSenderId: '926177753172',
    projectId: 'attendance-4e2af',
    storageBucket: 'attendance-4e2af.firebasestorage.app',
    iosClientId: '926177753172-hug2pn5oqqoe0i7r2dn76ijgo113ifvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJvS2mgyBkwtIRPBV5GSyIq9nqOhBRiw',
    appId: '1:926177753172:ios:543f9d1b0e9911593655c1',
    messagingSenderId: '926177753172',
    projectId: 'attendance-4e2af',
    storageBucket: 'attendance-4e2af.firebasestorage.app',
    iosClientId: '926177753172-hug2pn5oqqoe0i7r2dn76ijgo113ifvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUDc7RPDJ3gzzq1pdvyEH9lkwP3IIzMLI',
    appId: '1:926177753172:web:fc1cf635e0be29df3655c1',
    messagingSenderId: '926177753172',
    projectId: 'attendance-4e2af',
    authDomain: 'attendance-4e2af.firebaseapp.com',
    storageBucket: 'attendance-4e2af.firebasestorage.app',
    measurementId: 'G-T9MLK2J8TK',
  );
}
